#!/bin/sh

uci -q batch <<-EOF >/dev/null
    delete ucitrack.@freeradius[-1]
    add ucitrack freeradius
    set ucitrack.@freeradius[-1].exec="/usr/lib/freeradius.sh rebuild"
    commit ucitrack
EOF

/etc/init.d/ucitrack restart

/usr/lib/freeradius.sh rebuild
